# Generated by Django 4.1.5 on 2023-03-16 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contest_description_alter_contest_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='pushedcontest',
            name='task_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushedcontest',
            name='pushed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
