# Generated by Django 4.2.2 on 2023-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='problem_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
