# Generated by Django 4.2.2 on 2023-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0002_submissions_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetproblems',
            name='problem_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
