# Generated by Django 4.2.2 on 2023-06-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0003_cfusers_last_online_submissions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
