# Generated by Django 4.2.2 on 2023-06-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0005_alter_submissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfusers',
            name='last_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
