# Generated by Django 4.2.2 on 2023-06-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0006_alter_cfusers_last_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
