# Generated by Django 4.2.2 on 2023-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0007_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsolves',
            name='submission_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
